// Assignment6/src/components/PlayerHand.tsx
'use client'

import { Card, Color } from '@/lib/game/deck'
import UnoCard from './UnoCard'
import { useState } from 'react'

interface PlayerHandProps {
    name: string
    index: number
    isActive: boolean
    cards: Card[]
    onPlay: (cardIndex: number, namedColor?: Color) => void
}

export default function PlayerHand({ name, index, isActive, cards, onPlay }: PlayerHandProps) {
    const [wildChoice, setWildChoice] = useState<number | null>(null)

    const handleClick = (card: Card, idx: number) => {
        if (!card || !isActive) return

        if (card.type === 'WILD' || card.type === 'WILD DRAW') {
            setWildChoice(idx)
        } else {
            onPlay(idx)
        }
    }

    const chooseColor = (color: Color) => {
        if (wildChoice !== null) {
            onPlay(wildChoice, color)
            setWildChoice(null)
        }
    }

    return (
        <div
            className={`flex flex-col w-fit gap-2 px-10 py-4 rounded-lg transition-all ${!isActive ? 'opacity-50' : ''
                }`}
        >
            <p className="text-center text-3xl font-bold text-white">{name}</p>

            <div className="flex flex-row gap-1">
                {cards.map((card, idx) => (
                    <div key={idx} className="ml-[-20px]" onClick={() => handleClick(card, idx)}>
                        <UnoCard
                            card={card}
                            className={`transition-transform ${isActive ? 'hover:scale-105 hover:translate-y-[-8px]' : ''}`}
                        />
                    </div>
                ))}
            </div>

            {/* Wild card color picker */}
            {wildChoice !== null && (
                <div className="flex gap-2 mt-2 justify-center">
                    <button
                        className="w-12 h-12 transition-transform hover:scale-110 rounded bg-red-600"
                        onClick={() => chooseColor('RED')}
                    ></button>
                    <button
                        className="w-12 h-12 transition-transform hover:scale-110 rounded bg-yellow-400"
                        onClick={() => chooseColor('YELLOW')}
                    ></button>
                    <button
                        className="w-12 h-12 transition-transform hover:scale-110 rounded bg-green-600"
                        onClick={() => chooseColor('GREEN')}
                    ></button>
                    <button
                        className="w-12 h-12 transition-transform hover:scale-110 rounded bg-blue-600"
                        onClick={() => chooseColor('BLUE')}
                    ></button>
                </div>
            )}
        </div>
    )
}

// Assignment3/client/src/components/PlayerHand.vue
<script setup lang="ts">
import UnoCard from '@/components/UnoCard.vue'
import type { Card, Color } from '../../../domain/src/model/card'
import { ref } from 'vue'
import type { PlayCardApiProps } from '@/graphql/api'

export type PlayerHandProps = {
  playCardId: number
  name: string
  index: number
  isActive: boolean
  cards: Card[]
  onPlay: ({
    cardIndex,
    namedColor,
    playerIndex,
    playCardId,
  }: PlayCardApiProps) => void | Promise<void>
}

const props = defineProps<PlayerHandProps>()

// track wild selection UI locally
const wildChoice = ref<number | null>(null)

function handleClick(card: Card, idx: number) {
  if (!card) return
  if (!props.isActive) return

  if (card.type === 'WILD' || card.type === 'WILD DRAW') {
    wildChoice.value = idx
  } else {
    props.onPlay({
      cardIndex: idx,
      playCardId: props.playCardId,
      playerIndex: props.index,
      namedColor: card.color,
    })
  }
}

function chooseColor(color: Color) {
  if (wildChoice.value === null) return
  props.onPlay({
    cardIndex: wildChoice.value,
    playCardId: props.playCardId,
    playerIndex: props.index,
    namedColor: color,
  })
  wildChoice.value = null
}
</script>

<template>
  <div
    class="flex flex-col gap-2 px-10 py-4 rounded-lg transition-all"
    :class="{
      'opacity-50': !isActive,
    }"
  >
    <p class="text-center text-3xl font-bold text-white">{{ name }}</p>

    <div class="flex flex-row gap-1 pl-[30px]">
      <li v-for="(card, idx) in cards" :key="idx" @click="handleClick(card, idx)">
        <div class="ml-[-20px]">
          <UnoCard :card="card" />
        </div>
      </li>
    </div>

    <!-- Wild card picker -->
    <div v-if="wildChoice !== null" class="flex gap-2 mt-2">
      <button class="w-8 h-8 rounded bg-red-600" @click="chooseColor('RED')" />
      <button class="w-8 h-8 rounded bg-yellow-400" @click="chooseColor('YELLOW')" />
      <button class="w-8 h-8 rounded bg-green-600" @click="chooseColor('GREEN')" />
      <button class="w-8 h-8 rounded bg-blue-600" @click="chooseColor('BLUE')" />
    </div>
  </div>
</template>
