// Assignment3/client/src/components/BotHand.vue
<script setup lang="ts">
import UnoCard from '@/components/UnoCard.vue'
import type { Card } from '@/model/card'

defineProps<{
  name: string
  index: number
  isActive: boolean
  cards: Card[]
  orientation?: 'horizontal' | 'vertical' // flex row vs column
}>()
</script>

<template>
  <div
    class="flex gap-2 items-center transition-all"
    :class="{
      'opacity-50': !isActive,
      'flex-col': orientation === 'horizontal',
      'flex-row': orientation === 'vertical',
    }"
  >
    <!-- Cards (back only) -->
    <div :class="[orientation === 'horizontal' ? 'flex flex-row gap-1 ' : 'flex flex-col']">
      <div
        v-for="(_, idx) in cards"
        :key="idx"
        :class="[orientation === 'horizontal' ? '' : 'mb-[-110px]']"
      >
        <UnoCard back />
      </div>
    </div>

    <!-- Bot name -->
    <p class="text-center text-xl font-bold text-white">{{ name }}</p>
  </div>
</template>

// Assignment6/src/components/BotHand.tsx
'use client'

import { Card } from '@/lib/game/deck'
import UnoCard from './UnoCard'

interface BotHandProps {
    name: string
    index: number
    isActive: boolean
    cards: Card[]
    orientation?: 'horizontal' | 'vertical'
    className?: string
}

export default function BotHand({
    name,
    index,
    isActive,
    cards,
    orientation = 'horizontal',
    className = ''
}: BotHandProps) {
    return (
        <div
            className={`flex flex-col gap-3 items-center ${!isActive ? 'opacity-50' : ''} ${className}`}
        >
            <p className="text-3xl font-bold text-white mb-2">
                {name}
            </p>
            <div className={`flex ${orientation === 'vertical' ? 'flex-col' : 'flex-row'} gap-1`}>
                {cards.map((_, idx) => (
                    <div key={idx} className={orientation === 'vertical' ? '-mt-5' : '-ml-5'}>
                        <UnoCard back />
                    </div>
                ))}
            </div>
            <span className="text-white text-sm">({cards.length} cards)</span>
        </div>
    )
}
